### ISSUE TITLE
error: No applicable method

### ISSUE THREAD

**Issue by grolongo** [karthink/project-x#1]
Hello!

I was trying to use your function project-x-try-local outside of project-x, directly with the built-in project.el but I'm getting a weird error:

to reproduce,

1. use this snippet

```elisp
(use-package project ; if on 27.2 project.el v0.8.0 will get fetched from ELPA
  :ensure t
  :config
  (defun project-x-try-local (dir)
    "Determine if DIR is a non-VC project.
DIR must include a .project file to be considered a project."
    (if-let ((root (locate-dominating-file dir ".project")))
        (cons 'local root)))
  (add-hook 'project-find-functions 'project-x-try-local 90))
```

2. `C-x p p` then choose a non-vcs project (one with a .project at it's root)
3. press `[F]` or any other options

Error: `No applicable method: project-root, (local . "~/testproject/")`

Yet, when I'm using this snippet in the exact same init.el with the same Emacs version:

```elisp
(use-package project-x
  :load-path "~/.emacs.d/elpa/project-x/"
  :after project
  :config
  (add-hook 'project-find-functions 'project-x-try-local 90))
```

everything works fine. Do you have any idea what's happening? I'm so confused.

**Comment by karthink** [comment]
You also need a `project-root` method that [extracts the root of a local project](https://github.com/karthink/project-x/blob/master/project-x.el#L139):

```elisp
(cl-defmethod project-root ((project (head local)))
  "Return root directory of current PROJECT."
  (cdr project))
```

Try it with this included in your use-package declaration.

**Comment by grolongo** [comment]
@karthink thank you a lot. That completely fixes my issue.

Last unrelated question before I close this issue, do you plan to add project-x on ELPA/MELPA?

**Comment by karthink** [comment]
I would like to but I don't have the time for it right now. 

Also the project library for Emacs is under active development, which means project-x can break at any time. If it's on MELPA the expectation is that it will be updated right away after it breaks, and I won't be able to because of time.

**Comment by grolongo** [comment]
Understood. Thank you again.
