### ISSUE TITLE
Feature request: regex in project-x-local-identifier

### ISSUE THREAD

**Issue by olnw** [karthink/project-x#10]
It would be useful if we could specify local identifiers using regular expressions.

For example, most Common Lisp libraries have a `<library name>.asd` file in their root, which is a "system" definition, a bit like a Makefile. The requested feature would allow us to match any file with a certain extension, when the file's base name is unknown.

**Comment by aurtzy** [comment]
Hi! If this is still relevant to you: it looks like project.el upstream has recently introduced (I've just noticed this exists on 29.4) the `project-vc-extra-root-markers` list variable which accepts globs as well, so you could set it to something like `'("*.asd")`.

**Comment by olnw** [comment]
> Hi! If this is still relevant to you: it looks like project.el upstream has recently introduced (I've just noticed this exists on 29.4) the `project-vc-extra-root-markers` list variable which accepts globs as well, so you could set it to something like `'("*.asd")`.

Thanks! That's just what I was looking for.
