### ISSUE TITLE
Error When Switching To Local Project - File listing failed: FIND: Parameter format not correct

### ISSUE THREAD

**Issue by DownBackDad** [karthink/project-x#6]
I seem to be having issues with the local project capability of Project-X. I'm trying to use it with my Org file directory, which I sync with Dropbox instead of version control.

When I use the command "project-switch-project" and give my Org file directory, then select "find file", I get the error "File listing failed: FIND: Parameter format not correct".

I've reproduced this with the following minimal init.el file (project-x.el resides in the "project-x" folder specified"):

```
(add-to-list 'load-path "C:/Users/Kris/.emacs.d/project-x")

(with-eval-after-load 'project
  (require 'project-x)
  (project-x-mode +1))
```

I also created a basic test project directory to reproduce with, which includes a ".project" file and two test "*.org" files:

![image](https://user-images.githubusercontent.com/40786898/177258827-112c6198-f2c4-4d99-a5d4-1ec4dd5cdce7.png)

In this test state, when I run "project-switch-project", select the "ProjectTest" directory, then select the "Find file" option, I get the error "File listing failed: FIND: Parameter format not correct". Here is the debug trace after running "toggle-debug-on-error":

```
Debugger entered--Lisp error: (error "File listing failed: FIND: Parameter format not correct\n")
  signal(error ("File listing failed: FIND: Parameter format not co..."))
  error("File listing failed: %s" "FIND: Parameter format not correct\n")
  project--files-in-directory("~/ProjectTest/" ("SCCS/" "RCS/" "CVS/" "MCVS/" ".src/" ".svn/" ".git/" ".hg/" ".bzr/" "_MTN/" "_darcs/" "{arch}/" ".#*" "*.o" "*~" "*.bin" "*.bak" "*.obj" "*.map" "*.ico" "*.pif" "*.lnk" "*.a" "*.ln" "*.blg" "*.bbl" "*.dll" "*.drv" "*.vxd" "*.386" "*.elc" "*.lof" "*.glo" "*.idx" "*.lot" "*.fmt" "*.tfm" "*.class" "*.fas" "*.lib" "*.mem" "*.x86f" "*.sparcf" "*.dfsl" "*.pfsl" "*.d64fsl" "*.p64fsl" "*.lx64fsl" "*.lx32fsl" "*.dx64fsl" ...))
  #f(compiled-function (dir) #<bytecode 0x1b6db76fa26a4a24>)("~/ProjectTest/")
  mapcan(#f(compiled-function (dir) #<bytecode 0x1b6db76fa26a4a24>) ("~/ProjectTest/"))
  #f(compiled-function (project &optional dirs) #<bytecode 0x719864799b8e376>)((local . "~/ProjectTest/") ("~/ProjectTest/"))
  apply(#f(compiled-function (project &optional dirs) #<bytecode 0x719864799b8e376>) (local . "~/ProjectTest/") ("~/ProjectTest/"))
  project-files((local . "~/ProjectTest/") ("~/ProjectTest/"))
  project-find-file-in("Emacs" ("~/ProjectTest/") (local . "~/ProjectTest/"))
  project-find-file()
  funcall-interactively(project-find-file)
  project-switch-project("c:/Users/Kris/ProjectTest/")
  funcall-interactively(project-switch-project "c:/Users/Kris/ProjectTest/")
  command-execute(project-switch-project record)
  execute-extended-command(nil "project-switch-project" "project-switch-pro")
  funcall-interactively(execute-extended-command nil "project-switch-project" "project-switch-pro")
  command-execute(execute-extended-command)
```

I'm still cutting my teeth on elisp, so any advice on how to troubleshoot this further would be appreciated.

From my reading of the Project-X readme, it seems like I shouldn't have to do anything to enable the local project functionality other than enabling project-x-mode and having a .project file in the directory.

Edit:
Forgot to mention, I'm using Emacs 28.1 (Windows release) and project.el is version 0.8.1.

**Comment by karthink** [comment]
It looks like an issue with the `find` (shell) command or equivalent that your Emacs uses. Can you confirm that

- the variable `find-program` is bound to something valid in your Emacs, and that
- this only happens with "local" projects and not version-controlled ones?

**Comment by DownBackDad** [comment]
Correct, this only happened with "local" projects. I was able to successfully use project-switch-project on a git project directory.

The default value of find-program on Windows appears to be "find", but upon further searching around this it appears that the Windows find.exe program (located in C:\Windows\System32) does not play nicely with grep commands.

I was able to resolve this issue by adding the following to the init.el, as I already had Git installed and it comes with a Unix-compatible find.exe:

```
(setq find-program "\"C:\\Program Files\\Git\\usr\\bin\\find.exe\"")
```

Really this is just another reason for me to switch to using Emacs via WSL2 on Windows (but I'm waiting on support at work for that).

Thank you for pointing me in the right direction on this! Would you care for me to submit a PR to update the README's "Setup and customization" section to include this caveat for Windows users, or should I not bother?

**Comment by karthink** [comment]
> Would you care for me to submit a PR to update the README's "Setup and customization" section to include this caveat for Windows users, or should I not bother?

Adding this line to the Readme might be helpful for Windows users. If you're still interested in this, could you submit the PR?

But more generally, this find command is specified in project.el, not project-x, and is thus part of Emacs. Further, there's no mention of or accounting for the incompatibility with Windows' version of `find`. So I think this should ultimately be reported as a bug to emacs-devel. I don't use Windows right now so I can't test this. Would you be interested in sending a (short) bug report about the `project--files-in-directory` using `M-x report-emacs-bug`?
